#Hugo configuration
title = "qweadf"
baseURL = "https:\/\/ewqre.asd.er"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
